NumPy Assignment

In [7]:
import numpy as np
import random

1. A 1D NumPy array with integers from 1 to 20

In [ ]:
arr1 = np.arange(1, 21)
print("Array:", arr1)

print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

indices_get_10 = np.where(arr1 > 10)
print("Indices of elements > 10:", indices_gt_10)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


array is created using np.arange and it sum, mean, median and standard deviation are found out usinf np.sum(), np.mean(), np.median() and np.std() respectively.
then the indices of the no.s greater than 10 are found out using np.where().

2. 2D NumPy array of shape 4x4 with numbers from 1 to 16

In [3]:
arr2 = np.arange(1, 17).reshape(4, 4)

print("2D Array:\n", arr2)
print("Transpose:\n", arr2.transpose())
print("Row-wise sums:", np.sum(arr2, axis=1))
print("Column-wise sums:", np.sum(arr2, axis=0))

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


the array arr2 is created and sum is found out using np.sum(). 
axis 1 denots rows and axis 0 denotes columns.

## 3. Two 3x3 arrays filled with random integers between 1 and 20

In [9]:
l1=[]
l2=[]
for i in range(1,10):
    l1.append(random.randint(1, 21))
    l2.append(random.randint(1, 21))
arr3 = np.array(l1).reshape(3, 3)
arr4 = np.array(l2).reshape(3, 3)

print("Array 1:\n", arr3)
print("Array 2:\n", arr4)

print("Addition:\n", arr3 + arr4)
print("Subtraction:\n", arr3 - arr4)
print("Multiplication:\n", arr3 * arr4)

print("Dot Product:\n", arr3.dot(arr4))

Array 1:
 [[10 10 11]
 [14 13 16]
 [17 21  8]]
Array 2:
 [[ 1 21 14]
 [17 13  6]
 [11  7 10]]
Addition:
 [[11 31 25]
 [31 26 22]
 [28 28 18]]
Subtraction:
 [[  9 -11  -3]
 [ -3   0  10]
 [  6  14  -2]]
Multiplication:
 [[ 10 210 154]
 [238 169  96]
 [187 147  80]]
Dot Product:
 [[301 417 310]
 [411 575 434]
 [462 686 444]]


2 arrays are created. the element wise sum, difference and product is found out using simple operators. then the dot product is found out using np.dot().

4. Reshaping a 1D array of size 12 into a 3x4 2D array and slice

In [10]:
arr5 = np.arange(1, 13).reshape(3, 4)
print("Original 3x4 Array:\n", arr5)

sliced = arr5[:2, -2:]
print("Sliced (first 2 rows, last 2 cols):\n", sliced)

Original 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced (first 2 rows, last 2 cols):
 [[3 4]
 [7 8]]


array is created and then 1st two rows and last 2 columns are sliced out.