# NumPy Assignment

In [2]:
import numpy as np

## 1. Create a 1D NumPy array with integers from 1 to 20

In [3]:
arr1 = np.arange(1, 21)
print("Array:", arr1)

print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

indices_gt_10 = np.where(arr1 > 10)
print("Indices of elements > 10:", indices_gt_10)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


array is created using np.arange and it sum, mean, median and standard deviation are found out usinf np.sum(), np.mean(), np.median() and np.std() respectively.
then the indices of the no.s greater than 10 are found out using np.where().

## 2. Create a 2D NumPy array of shape 4x4 with numbers from 1 to 16

In [4]:
arr2 = np.arange(1, 17).reshape(4, 4)

print("2D Array:\n", arr2)
print("Transpose:\n", arr2.T)
print("Row-wise sums:", np.sum(arr2, axis=1))
print("Column-wise sums:", np.sum(arr2, axis=0))

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


the array arr2 is created and sum is found out using np.sum(). 
axis 1 denots rows and axis 0 denotes columns.

## 3. Create two 3x3 arrays filled with random integers between 1 and 20

In [5]:
arr3 = np.random.randint(1, 21, (3, 3))
arr4 = np.random.randint(1, 21, (3, 3))

print("Array 1:\n", arr3)
print("Array 2:\n", arr4)

print("Addition:\n", arr3 + arr4)
print("Subtraction:\n", arr3 - arr4)
print("Multiplication:\n", arr3 * arr4)

print("Dot Product:\n", np.dot(arr3, arr4))

Array 1:
 [[13 13  9]
 [15 16 18]
 [ 6  9  6]]
Array 2:
 [[19 18 18]
 [20 10  5]
 [ 3  8  5]]
Addition:
 [[32 31 27]
 [35 26 23]
 [ 9 17 11]]
Subtraction:
 [[-6 -5 -9]
 [-5  6 13]
 [ 3  1  1]]
Multiplication:
 [[247 234 162]
 [300 160  90]
 [ 18  72  30]]
Dot Product:
 [[534 436 344]
 [659 574 440]
 [312 246 183]]


2 arrays are created. the element wise sum, difference and product is found out using simple operators. then the dot product is found out using np.dot().

## 4. Reshape a 1D array of size 12 into a 3x4 2D array and slice

In [6]:
arr5 = np.arange(1, 13).reshape(3, 4)
print("Original 3x4 Array:\n", arr5)

sliced = arr5[:2, -2:]
print("Sliced (first 2 rows, last 2 cols):\n", sliced)

Original 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced (first 2 rows, last 2 cols):
 [[3 4]
 [7 8]]


array is created and then 1st two rows and last 2 columns are sliced out.